-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('TestA_pb')


local TESTA = protobuf.Descriptor();
local TESTA_ID_FIELD = protobuf.FieldDescriptor();
local TESTA_NAME_FIELD = protobuf.FieldDescriptor();
local TESTA_YEAR_FIELD = protobuf.FieldDescriptor();
local TESTA_NETTYPE_FIELD = protobuf.FieldDescriptor();

TESTA_ID_FIELD.name = "id"
TESTA_ID_FIELD.full_name = ".Google.TestA.id"
TESTA_ID_FIELD.number = 1
TESTA_ID_FIELD.index = 0
TESTA_ID_FIELD.label = 2
TESTA_ID_FIELD.has_default_value = false
TESTA_ID_FIELD.default_value = 0
TESTA_ID_FIELD.type = 13
TESTA_ID_FIELD.cpp_type = 3

TESTA_NAME_FIELD.name = "name"
TESTA_NAME_FIELD.full_name = ".Google.TestA.name"
TESTA_NAME_FIELD.number = 2
TESTA_NAME_FIELD.index = 1
TESTA_NAME_FIELD.label = 1
TESTA_NAME_FIELD.has_default_value = false
TESTA_NAME_FIELD.default_value = 0
TESTA_NAME_FIELD.type = 13
TESTA_NAME_FIELD.cpp_type = 3

TESTA_YEAR_FIELD.name = "year"
TESTA_YEAR_FIELD.full_name = ".Google.TestA.year"
TESTA_YEAR_FIELD.number = 3
TESTA_YEAR_FIELD.index = 2
TESTA_YEAR_FIELD.label = 2
TESTA_YEAR_FIELD.has_default_value = false
TESTA_YEAR_FIELD.default_value = ""
TESTA_YEAR_FIELD.type = 9
TESTA_YEAR_FIELD.cpp_type = 9

TESTA_NETTYPE_FIELD.name = "nettype"
TESTA_NETTYPE_FIELD.full_name = ".Google.TestA.nettype"
TESTA_NETTYPE_FIELD.number = 4
TESTA_NETTYPE_FIELD.index = 3
TESTA_NETTYPE_FIELD.label = 1
TESTA_NETTYPE_FIELD.has_default_value = false
TESTA_NETTYPE_FIELD.default_value = 0
TESTA_NETTYPE_FIELD.type = 13
TESTA_NETTYPE_FIELD.cpp_type = 3

TESTA.name = "TestA"
TESTA.full_name = ".Google.TestA"
TESTA.nested_types = {}
TESTA.enum_types = {}
TESTA.fields = {TESTA_ID_FIELD, TESTA_NAME_FIELD, TESTA_YEAR_FIELD, TESTA_NETTYPE_FIELD}
TESTA.is_extendable = false
TESTA.extensions = {}

TestA = protobuf.Message(TESTA)

