-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('TestB_pb')


local TESTB = protobuf.Descriptor();
local TESTB_AA_FIELD = protobuf.FieldDescriptor();
local TESTB_BB_FIELD = protobuf.FieldDescriptor();
local TESTB_CC_FIELD = protobuf.FieldDescriptor();

TESTB_AA_FIELD.name = "aa"
TESTB_AA_FIELD.full_name = ".Google.TestB.aa"
TESTB_AA_FIELD.number = 1
TESTB_AA_FIELD.index = 0
TESTB_AA_FIELD.label = 2
TESTB_AA_FIELD.has_default_value = false
TESTB_AA_FIELD.default_value = 0
TESTB_AA_FIELD.type = 13
TESTB_AA_FIELD.cpp_type = 3

TESTB_BB_FIELD.name = "bb"
TESTB_BB_FIELD.full_name = ".Google.TestB.bb"
TESTB_BB_FIELD.number = 2
TESTB_BB_FIELD.index = 1
TESTB_BB_FIELD.label = 1
TESTB_BB_FIELD.has_default_value = false
TESTB_BB_FIELD.default_value = 0
TESTB_BB_FIELD.type = 13
TESTB_BB_FIELD.cpp_type = 3

TESTB_CC_FIELD.name = "cc"
TESTB_CC_FIELD.full_name = ".Google.TestB.cc"
TESTB_CC_FIELD.number = 3
TESTB_CC_FIELD.index = 2
TESTB_CC_FIELD.label = 2
TESTB_CC_FIELD.has_default_value = false
TESTB_CC_FIELD.default_value = ""
TESTB_CC_FIELD.type = 9
TESTB_CC_FIELD.cpp_type = 9

TESTB.name = "TestB"
TESTB.full_name = ".Google.TestB"
TESTB.nested_types = {}
TESTB.enum_types = {}
TESTB.fields = {TESTB_AA_FIELD, TESTB_BB_FIELD, TESTB_CC_FIELD}
TESTB.is_extendable = false
TESTB.extensions = {}

TestB = protobuf.Message(TESTB)

